version: '3.8'
services:
  service1:
    container_name: spring-petclinic-angular
    image: plzwork.azurecr.io/spring-petclinic-angular
    build: ./frontend/spring-petclinic-angular
    ports:
    - target: 8080
      published: 8080
      protocol: tcp
    deploy:
      replicas: 3
  service2:
    container_name: spring-petclinic-rest
    image: plzwork.azurecr.io/spring-petclinic-rest
    build: ./backend/spring-petclinic-rest
    deploy:
      replicas: 3