apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-angular
  namespace: plzworkplz
spec:
  selector:
    app: spring-petclinic-angular
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-angular
  namespace: plzworkplz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic-angular
  template:
    metadata:
      labels:
        app: spring-petclinic-angular
    spec:
      containers:
      - name: spring-petclinic-angular
        image: plzwork.azurecr.io/spring-petclinic-angular
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: plzwork4851c18a-auth