apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: plzworkplz
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: plzworkplz
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
      - containerPort: 3306
        name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: petclinic
      - name: MYSQL_DATABASE
        value: petclinic
      - name: spring.datasource.url
        value: jdbc:mysql://localhost:3306/petclinic?useUnicode=true