apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: plzworkplz
  labels: 
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: plzworkplz
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: plzworkplz
data:
  default.conf: |
    server {
        listen 80;
        location / {
          proxy_pass http://spring-petclinic-angular:8080/petclinic/;
        }
        location /petclinic/api/ {
          proxy_pass http://spring-petclinic-rest:9966/petclinic/api/;
        }
    }
